global:
  resolve_timeout: 1m

route:
  receiver: jenkins-rollback-webhook
  group_wait: 0s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://YOUR_EC2_PUBLIC_IP:8080/generic-webhook-trigger/invoke?token=ROLLBACK_ACB434_TOKEN'
        send_resolved: false
        http_config:
          basic_auth:
            username: 'YOUR_JENKINS_USERNAME'
            password: 'YOUR_JENKINS_API_TOKEN'
