global:
  resolve_timeout: 1m

route:
  receiver: jenkins-rollback-webhook
  group_wait: 0s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://35.154.192.217:8080/generic-webhook-trigger/invoke?token=ROLLBACK_ACB434_TOKEN'
        send_resolved: false
        http_config:
          basic_auth:
            username: 'admin'
            password: '1105b128c1088f875d7509e504cdf0414d'
